### ISSUE TITLE
python3 atlas.py --url https://personal.idm.eur.nl/user/anonlogin.jsp;jsessionid=A33675EEFC516F7C144BBD178675E69F?next=user/anonWorkItemEdit.jsp&id=Price_ASC --payload="-1234 AND 4321=4321-- AAAA" --random-agent -v [23:15:46] [WARN] Please set payload with "-p|--payload" options [1]+  Done                    jsessionid=A33675EEFC516F7C144BBD178675E69F?next=user/anonWorkItemEdit.jsp [1] 4042 -bash: --payload=-1234 AND 4321=4321-- AAAA: command not found

### ISSUE THREAD

**Issue by sabeesh03** [m4ll0k/Atlas#17]
python3 atlas.py --url https://abcp.com/;jsessionid=A33675EEFC516F7C144BBD178675E69F?next=user/anonWorkItemEdit.jsp&id=Price_ASC --payload="-1234 AND 4321=4321-- AAAA" --random-agent -v
[23:15:46] [WARN] Please set payload with "-p|--payload" options
[1]+  Done                    jsessionid=A33675EEFC516F7C144BBD178675E69F?next=user/anonWorkItemEdit.jsp
[1] 4042
-bash: --payload=-1234 AND 4321=4321-- AAAA: command not found

**Comment by m4ll0k** [comment]
try with quotes: like ` python3 atlas.py --url "https://..." --payload "-1234 ..." --random-agent -v `
