### ISSUE TITLE
Shell

### ISSUE THREAD

**Issue by SantaLaMuerte** [m4ll0k/Atlas#19]
Hello.
plz add a shell (constant menu like --sqlmap-shell) for working in powershell in win os. it will be very helpfull - little hard to alias comand for atlas.py (maybe someone can help)
i made a bat file --
powershell -NoExit py 'C:\Users\*\Desktop\Atlas-master\atlas.py'" 

but i need again write *py atlas.py -comand..*  Dunnow how to make it perfect and easy for work in winpwshl
Thanks for your work!

**Comment by SantaLaMuerte** [comment]
for sqlmap it is 
C:
cd C:\Users\Desktop\sqlmap-master
cls
sqlmap.py --sqlmap-shell

and then i can easy work with map. hope this comment will help someone (sorry for offtopic)

**Comment by m4ll0k** [comment]
ok @hastalamuerte
