### ISSUE TITLE
Another Syntax Error

### ISSUE THREAD

**Issue by Creepygreen45** [m4ll0k/Atlas#21]
I typed `python3 atlas.py` and I got back:

`Traceback (most recent call last):
  File "C:\***\***\***\Atlas-master\atlas.py", line 16, in <module>
    from humanfriendly.tables import format_pretty_table as pretty
ModuleNotFoundError: No module named 'humanfriendly'`

The exact version of python that I'm using is 3.9.1 
As a side question, which version of python is Atlas currently on?

**Comment by m4ll0k** [comment]
install `humanfriendly `
